# Generated by Django 3.2.6 on 2021-08-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_alter_comment_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.CharField(max_length=22, null=True, verbose_name='评论对象ID'),
        ),
    ]
