# Generated by Django 3.2.6 on 2021-09-17 01:24

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='评论'),
        ),
    ]
