# Generated by Django 3.2.5 on 2021-08-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnippetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-create_time'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ['-create_time'], 'verbose_name': '代码片段', 'verbose_name_plural': '代码片段'},
        ),
        migrations.AlterModelOptions(
            name='snippetcategory',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AddField(
            model_name='snippet',
            name='tag',
            field=models.ManyToManyField(to='snippet.SnippetTag'),
        ),
    ]
