# Generated by Django 3.2.6 on 2021-08-25 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag_type',
        ),
    ]
