# Generated by Django 3.2.5 on 2021-08-19 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0002_auto_20210819_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='category',
        ),
        migrations.DeleteModel(
            name='SnippetCategory',
        ),
    ]
