# Generated by Django 3.2.5 on 2021-08-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0003_auto_20210819_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippettag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
