# Generated by Django 3.2.5 on 2021-08-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0004_alter_snippettag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='snippet.SnippetTag'),
        ),
    ]
