# Generated by Django 3.2.6 on 2021-08-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0004_article_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-order'], 'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AddField(
            model_name='tag',
            name='order',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='排序'),
        ),
    ]
