# Generated by Django 3.2.6 on 2021-08-30 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0005_auto_20210827_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['order', 'id'], 'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
    ]
