# Generated by Django 3.2.5 on 2021-08-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0005_alter_snippet_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='tag',
            field=models.ManyToManyField(to='snippet.SnippetTag'),
        ),
    ]
