# Generated by Django 3.2.6 on 2021-09-05 07:55

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0006_alter_tag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='正文'),
        ),
    ]
