# Generated by Django 3.2.5 on 2021-08-21 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0006_alter_snippet_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
