# Generated by Django 3.2.6 on 2021-09-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0008_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(help_text='标签按住 win 的 Control 键或者 Mac 的 Command 键可多选', to='snippet.Tag', verbose_name='标签'),
        ),
    ]
