# Generated by Django 3.2.6 on 2021-09-17 01:24

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0009_alter_article_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='正文'),
        ),
    ]
