# Generated by Django 3.2.5 on 2021-08-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aniuser',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='手机号码'),
        ),
    ]
