# Generated by Django 3.2.6 on 2021-09-07 07:47

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aniuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aniuser',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
