# Generated by Django 3.2.5 on 2021-08-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniuser', '0002_alter_aniuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aniuser',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='手机号码'),
        ),
    ]
